# version: '3'

# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     depends_on:
#       - localdb

#   localdb:
#     image: postgres:latest
#     environment:
#       - POSTGRES_USER=user
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_DB=database_name
#     volumes:
#       - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:

version: '3'

services:
  web:
    build:
      context: ./nbhw-backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .h/nbhw-backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - localdb

  localdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database_name
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
