version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - localdb

  localdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database_name
    volumes:
      - db_data:/var/lib/postgresql/data

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest
    volumes:
      - .:/app
    depends_on:
      - localdb

volumes:
  db_data:
